### ISSUE TITLE
按你这个demo跑了一遍报异常了

### ISSUE THREAD

**Issue by flyDuan** [brandonbai/mqtt-spring-boot#1]
![微信图片_20190326153625](https://user-images.githubusercontent.com/26811268/54979026-fe569f80-4fdc-11e9-968d-a64747f88b1b.png)

**Comment by brandonbai** [comment]
你好，这可能是版本的问题，我先看一下，晚些回复 @flyDuan

**Comment by brandonbai** [comment]
@flyDuan 麻烦提供下详细点的信息，目前运行了三个示例工程都没有报截图中的错。
